### ISSUE TITLE
Unable to fetch BlueSSLService

### ISSUE THREAD

**Issue by robm92** [IBM-Swift/BlueSSLService#23]
Using the following package.swift file:

> import PackageDescription
> let package = Package(
>     name: "project5",
>     dependencies: [
>         .Package(url: "https://github.com/IBM-Swift/Kitura.git",majorVersion: 1),
>         .Package(url: "https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git", majorVersion: 1),
>         .Package(url: "https://github.com/IBM-Swift/HeliumLogger.git", majorVersion: 1)
>     ]
> )

running 'swift build' gets stuck on the following and the swift build process

> Fetching https://github.com/IBM-Swift/Kitura.git
> Fetching https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git
> Fetching https://github.com/IBM-Swift/HeliumLogger.git
> Fetching https://github.com/twostraws/SwiftGD.git
> Fetching https://github.com/IBM-Swift/Kitura-net.git
> Fetching https://github.com/IBM-Swift/SwiftyJSON.git
> Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
> Fetching https://github.com/IBM-Swift/LoggerAPI.git
> Fetching https://github.com/IBM-Swift/BlueSocket.git
> Fetching https://github.com/IBM-Swift/CCurl.git
> **Fetching https://github.com/IBM-Swift/BlueSSLService.git**

The swift-build process then begins to consume memory and CPU usage

**Comment by robm92** [comment]
I just ran the same thing this morning and all is working as it should. 
I'm afraid I don't know why but perhaps there were some teething issues with Swift 3.1 that were resolved?

**Comment by leanne63** [comment]
I'm having this same problem intermittently. This was happening last week, and I thought it was something about my setup. Then, it started working, and has been working just fine until about an hour ago. Now, it won't fetch. I've been able to fetch all the other packages for my project, but it just gets stuck on this one, acting as though it's in an infinite loop.

I can't imagine what's happening. It's just retrieving files, yeah? Maybe this package is on a server that's going bad or suddenly becoming very busy?

**Comment by leanne63** [comment]
Here's where it sits, cursor blinking, Terminal title bar flashing:

```
$ swift build
Fetching https://github.com/IBM-Swift/Kitura.git
Fetching https://github.com/IBM-Swift/HeliumLogger.git
Fetching https://github.com/IBM-Swift/Swift-SMTP.git
Fetching https://github.com/IBM-Swift/Kitura-net.git
Fetching https://github.com/IBM-Swift/SwiftyJSON.git
Fetching https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Fetching https://github.com/IBM-Swift/LoggerAPI.git
Fetching https://github.com/IBM-Swift/BlueSocket.git
Fetching https://github.com/IBM-Swift/CCurl.git
Fetching https://github.com/IBM-Swift/BlueSSLService.git

```

I `ctrl-c` to exit eventually, wait awhile, then try again, but still not working

**Comment by leanne63** [comment]
For anyone who comes here later: my particular issue was caused by an invalid tag in Swift-SMTP.

To troubleshoot, I used `swift build -v`, which gives a (very) verbose listing of what's happening in the build process.

It was indeed looping, trying to fulfill the version dependency but blocked by the invalid tag.

**Comment by crspybits** [comment]
@leanne63 It sounds like you were seeing ongoing output, indicating looping. I'm seeing build hang at a fetch, but with the -v option, I see no ongoing output. In my case the build hangs at a different library (Fetching https://github.com/IBM-Swift/HeliumLogger.git).

**Comment by crspybits** [comment]
Well. It seems I spoke too soon. It just took a long time after the last Fetch. Maybe 10-20 minutes?

**Comment by leanne63** [comment]
This hang is the Swift Package Manager's way of indicating dependency hell. The trick is finding the one causing the problem. Use the `-v` option to get some ideas. Also, you might manually walk through your dependencies and their sub-dependencies. One of them is invalid or can't be resolved due to a conflict of some sort. In my case it was a bad tag; however, it's more likely to be two versions that can't get along.
